#!/usr/bin/env python3
"""The names of the hints as a C header, for a port that runs over the
program's own memory image (runtime/rmem.h).

    symmap.py OUT.h PREFIX KEY=HINTS [KEY=HINTS...] [--check]

The C refers to variables, records and routines by their names in the
hints; this writes where each name is, so that the C never holds a bare
address, and one C source can run several builds of one engine (one
KEY=HINTS pair each; the names are matched by name).  For each program:

  * KEY_EXE (its path in the game's files), KEY_SIZE and KEY_SHA256 (the
    loader checks that it is the file the hints describe), KEY_<SEG> the
    frame of each segment;
  * PREFIX_NAMES(X): X(SEG, name, address in the first program, in the
    second, ...) for every `name` and named `code` of any of the hints,
    0xFFFF where a program has no such name.  SEG is the segment's name
    in the first program that has the name;
  * with more than one program, PREFIX_FRAMES(X): X(SEG, name, frame in
    the first program, in the second, ...), the frames of the segment each
    program keeps the name in (the programs may name their segments
    otherwise: a module is T2354 in one and T0559 in another).

For a pMAX or raw 32-bit image (runtime/pmem.h) KEY_<SEG> is the segment's descriptor
number and the addresses are 32-bit offsets in it; a program without a
name has 0xFFFFFFFF there (outside an int: a port with several programs
keeps these in uint32_t, not an enum).

Only addresses and a hash go into the header, no bytes of the game.  The
header's first line records the arguments, so that check.py finds it and
runs this again with --check (exit status 1 when it is out of date).
Names that only some programs have are listed on stderr (not with
--check).
"""
import hashlib, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from disasm import Hints, program_path
from kit import project_root

TAG = 'generated by symmap.py:'


def program_info(key, h):
    data = open(program_path(h.exe), 'rb').read()
    lines = [f'#define {key}_EXE "{h.exe}"',
             f'#define {key}_SIZE {len(data)}u',
             f'#define {key}_SHA256 "{hashlib.sha256(data).hexdigest()}"']
    for s in h.segs:
        lines.append(f'#define {key}_{s.name} 0x{s.frame:04X}u')
    return lines


def generate(args, prefix, progs, quiet=False):
    hs = [Hints(os.path.join(project_root(), p)) for _, p in progs]
    guard = f'{prefix}_SYMMAP_H'
    out = [f'/* {TAG} {" ".join(args)}',
           ' * Where the names of the hints are in each program.  No game data.',
           ' * Do not edit: rerun the tool. */',
           f'#ifndef {guard}', f'#define {guard}', '']
    for (key, _), h in zip(progs, hs):
        out += program_info(key, h) + ['']
    seg_order = []
    for h in hs:
        for s in h.segs:
            if s.name not in seg_order:
                seg_order.append(s.name)
    # name -> address per program; a name keeps one segment in all
    none = 0xFFFFFFFF if any(h.kind in ('pmax', 'bin') for h in hs) else 0xFFFF
    names, seg_of, segs_in = {}, {}, {}
    for i, h in enumerate(hs):
        found = [(seg, off, name) for (seg, off), name in h.names.items()]
        found += [(seg, off, name) for seg, off, name in h.code if name]
        for seg, off, name in found:
            seg_of.setdefault(name, seg)        # the first program's segment names it
            segs_in.setdefault(name, [None] * len(hs))[i] = seg
            names.setdefault(name, [None] * len(hs))[i] = off
    for n in sorted(names) if not quiet and len(hs) > 1 else []:
        missing = [progs[i][0] for i, a in enumerate(names[n]) if a is None]
        if missing:
            print(f'not in {", ".join(missing)}: {seg_of[n]}:{n}', file=sys.stderr)
    keys = ', '.join(k for k, _ in progs)
    out.append(f'/* X(SEG, name, {keys}), in the order of the first program\'s addresses */')
    out.append(f'#define {prefix}_NAMES(X) \\')
    order = sorted(names, key=lambda n: (seg_order.index(seg_of[n]),
                                         [a if a is not None else none + 1 for a in names[n]], n))
    for n in order:
        a = ', '.join('0x%04X' % (v if v is not None else none) for v in names[n])
        out.append(f'    X({seg_of[n]}, {n}, {a}) \\')
    if len(hs) > 1:
        # a program may call the segment of a name otherwise (its frames
        # are what the names' segments are in each program)
        out += ['', f'/* X(SEG, name, {keys}): the frame of the name segment in each program */',
                f'#define {prefix}_FRAMES(X) \\']
        for n in order:
            f = ', '.join(f'{k}_{sg}' if sg else '0x%04X' % none
                          for (k, _), sg in zip(progs, segs_in[n]))
            out.append(f'    X({seg_of[n]}, {n}, {f}) \\')
    out += ['', '#endif', '']
    return '\n'.join(out)


def main():
    argv = sys.argv[1:]
    check = '--check' in argv
    args = [a for a in argv if a != '--check']
    if len(args) < 3 or any('=' not in a for a in args[2:]):
        raise SystemExit(__doc__)
    out_path, prefix = args[0], args[1]
    progs = [tuple(a.split('=', 1)) for a in args[2:]]
    path = os.path.join(project_root(), out_path)
    text = generate(args, prefix, progs, quiet=check)
    if check:
        old = open(path, encoding='utf-8').read() if os.path.exists(path) else ''
        if old != text:
            print(f'{out_path} out of date: run tools/symmap.py {" ".join(args)}')
            sys.exit(1)
        print(f'{out_path} up to date')
        return
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print(f'{out_path}: {text.count(chr(10) + "    X(")} names')


if __name__ == '__main__':
    main()
